name: Branch Naming

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        uses: actions/github-script@v6
        with:
           allowed_prefixes: 'feature/'
